/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Volunteer;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Reporting.CommonReporting.ChildrenDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.Police.PoliceViewReportingJPanel;

/**
 *
 * @author Lucifer
 */
public class VolunteerAdminJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form VolunteerAdminJPanel1
     */
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem; 
    private UserAccount userAccount;
     private ChildrenDirectory childrenDirectory;
    
    public VolunteerAdminJPanel1(JPanel userProcessContainer, EcoSystem ecoSystem, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        this.childrenDirectory = ecoSystem.getChildrenDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmissing = new javax.swing.JButton();
        btnfound = new javax.swing.JButton();

        btnmissing.setText("Missing Children");
        btnmissing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmissingActionPerformed(evt);
            }
        });

        btnfound.setText("Found Children");
        btnfound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnmissing, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(btnfound, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmissing, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfound, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(417, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnmissingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmissingActionPerformed
        // TODO add your handling code here:
        VolunteerMissingChildrenJPanel view = new VolunteerMissingChildrenJPanel(userProcessContainer, ecoSystem,userAccount);
        userProcessContainer.add("ViewReportingsJPanel", view);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnmissingActionPerformed

    private void btnfoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfoundActionPerformed
        // TODO add your handling code here:
        VolunteerFoundChildrenJPanel view = new VolunteerFoundChildrenJPanel(userProcessContainer, ecoSystem,userAccount);
        userProcessContainer.add("ViewReportingsJPanel", view);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnfoundActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfound;
    private javax.swing.JButton btnmissing;
    // End of variables declaration//GEN-END:variables
}
