/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Police;

import Business.EcoSystem;
import Business.Order.Order;
import Business.Order.OrderDirectory;
import Business.Restaurant.Item;
import Business.Restaurant.Menu;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mzhao
 */
public class PoliceAdminJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem; 
    private Menu menuDirectory;
    private UserAccount userAccount;
    private OrderDirectory orderDirectory;
    private RestaurantDirectory restaurantDirectory;
    /**
     * Creates new form ManageOrdersJPanel
     */
    public PoliceAdminJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;

        populateTable();
        populateComboBox();
        
        tableChildren.getTableHeader().setOpaque(false);
        tableChildren.getTableHeader().setBackground(Color.ORANGE);
    }

    public void populateTable(){
//        DefaultTableModel model = (DefaultTableModel)tableOrders.getModel();
//        model.setRowCount(0);
//        
//        for(Order order : orderDirectory.getOrderDirectory()){
//            if(order.getRestaurant().getUsername().equals(userAccount.getUsername())) {
//                Object [] row = new Object[5];
//                row[0] = order;
//                row[1] = order.getCustomer().getName();
//                
//                String items = "";
//                for (Item key : order.getItems().keySet()){
//                    items += key.getName();
//                    items += ",";
//                }
//                row[2] = items.substring(0, items.length() - 1);
//                row[3] = order.getPrice();
//                row[4] = order.getStatus();
//                
//                model.addRow(row);
//            }
//        }
    }
    
    public void populateComboBox() {
//        comboBoxDeliveryMan.removeAllItems();
//        comboBoxDeliveryMan.addItem("-Select One-");
//        for(DeliveryMan d : ecoSystem.getDeliveryManDirectory().getDeliveryManDirectory()) {
//            comboBoxDeliveryMan.addItem(d.getName());
//        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableChildren = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnDecline = new javax.swing.JButton();
        btnFinished = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Police Admin Missing Children Database");
        add(jLabel1);
        jLabel1.setBounds(200, 50, 480, 40);

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(708, 46, 93, 29);

        tableChildren.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Approx. Age", "Sex", "Race", "Found Date", "Found Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableChildren);
        if (tableChildren.getColumnModel().getColumnCount() > 0) {
            tableChildren.getColumnModel().getColumn(0).setResizable(false);
            tableChildren.getColumnModel().getColumn(1).setResizable(false);
            tableChildren.getColumnModel().getColumn(2).setResizable(false);
            tableChildren.getColumnModel().getColumn(3).setResizable(false);
            tableChildren.getColumnModel().getColumn(4).setResizable(false);
            tableChildren.getColumnModel().getColumn(5).setResizable(false);
            tableChildren.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane2);
        jScrollPane2.setBounds(87, 161, 714, 229);

        btnAccept.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnAccept.setText("Add Missing Child");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept);
        btnAccept.setBounds(141, 406, 168, 29);

        btnDecline.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnDecline.setText("Update Status");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });
        add(btnDecline);
        btnDecline.setBounds(375, 406, 139, 29);

        btnFinished.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnFinished.setText("View Details");
        btnFinished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishedActionPerformed(evt);
            }
        });
        add(btnFinished);
        btnFinished.setBounds(578, 406, 126, 29);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Search By Name:");
        add(jLabel2);
        jLabel2.setBounds(270, 110, 112, 17);
        add(jTextField1);
        jTextField1.setBounds(400, 110, 176, 26);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       userProcessContainer.remove(this);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        int selectedRow = tableChildren.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this,"Please select an order first.");
            return;
        }
        
        Order order = (Order) tableChildren.getValueAt(selectedRow, 0);
        order.setStatus("Order Accepted");
        populateTable();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        int selectedRow = tableChildren.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this,"Please select an order first.");
            return;
        }
        
        Order order = (Order) tableChildren.getValueAt(selectedRow, 0);
        order.setStatus("Order Declined");
        populateTable();
    }//GEN-LAST:event_btnDeclineActionPerformed

    private void btnFinishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishedActionPerformed
        int selectedRow = tableChildren.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this,"Please select an order first.");
            return;
        }
        
        Order order = (Order) tableChildren.getValueAt(selectedRow, 0);
        if (!order.getStatus().equals("Order Accepted")){
            JOptionPane.showMessageDialog(this, "Invalid choice of order.");
            return;
        }
        order.setStatus("Order Finished Cooking");
        populateTable();
    }//GEN-LAST:event_btnFinishedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDecline;
    private javax.swing.JButton btnFinished;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableChildren;
    // End of variables declaration//GEN-END:variables
}
