/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Clinic.Admin.Clinic;
import Donation.Donation;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gyt
 */
public class ViewDonationsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDonationsJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    
    public ViewDonationsJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        
        populateAllTable();
        if(rbtnPublic.isSelected()==true) populateAllTable();
        if(rbtnOrg.isSelected()==true) populateAllTable();
        
        double allamount =0;
        for(Donation d : ecosystem.getDonationDirectory().getDonationList()){
            allamount=allamount+d.getAmount();
        }
        
        double publicamount =0;
        for(Donation d : ecosystem.getDonationDirectory().getDonationList()){
            if(d.isIsPublic()==true) publicamount=publicamount+d.getAmount();            
        }
        
        double orgamount =0;
        for(Donation d : ecosystem.getDonationDirectory().getDonationList()){
            if(d.isIsPublic()==false) orgamount=orgamount+d.getAmount();            
        }
        
        lblOrg.setText(String.valueOf(orgamount));
        lblPublic.setText(String.valueOf(publicamount));
        lblTotal.setText(String.valueOf(allamount));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDonations = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPublic = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblOrg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbtnAll = new javax.swing.JRadioButton();
        rbtnPublic = new javax.swing.JRadioButton();
        rbtnOrg = new javax.swing.JRadioButton();
        txtDonor = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("View Donations");

        tableDonations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Donor", "Amount", "Date"
            }
        ));
        jScrollPane1.setViewportView(tableDonations);

        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("in total:");

        lblTotal.setForeground(new java.awt.Color(255, 204, 51));
        lblTotal.setText("jLabel3");

        jLabel4.setForeground(new java.awt.Color(255, 204, 51));
        jLabel4.setText(",");

        lblPublic.setForeground(new java.awt.Color(255, 204, 51));
        lblPublic.setText("jLabel5");

        jLabel6.setForeground(new java.awt.Color(255, 204, 51));
        jLabel6.setText("form public,");

        lblOrg.setForeground(new java.awt.Color(255, 204, 51));
        lblOrg.setText("jLabel7");

        jLabel8.setForeground(new java.awt.Color(255, 204, 51));
        jLabel8.setText("from organizations.");

        rbtnAll.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(rbtnAll);
        rbtnAll.setForeground(new java.awt.Color(255, 204, 51));
        rbtnAll.setText("all donations");
        rbtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAllActionPerformed(evt);
            }
        });

        rbtnPublic.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(rbtnPublic);
        rbtnPublic.setForeground(new java.awt.Color(255, 204, 51));
        rbtnPublic.setText("public donations");
        rbtnPublic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPublicActionPerformed(evt);
            }
        });

        rbtnOrg.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(rbtnOrg);
        rbtnOrg.setForeground(new java.awt.Color(255, 204, 51));
        rbtnOrg.setText("organization donations");
        rbtnOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOrgActionPerformed(evt);
            }
        });

        txtDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonorActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setForeground(new java.awt.Color(255, 204, 51));
        btnSearch.setText("search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 204, 51));
        jButton2.setText("<<Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2)
                                .addGap(147, 147, 147)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPublic)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblOrg)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDonor, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSearch)))))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnPublic)
                                    .addComponent(rbtnAll)
                                    .addComponent(rbtnOrg))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotal)
                    .addComponent(jLabel4)
                    .addComponent(lblPublic)
                    .addComponent(jLabel6)
                    .addComponent(lblOrg)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(rbtnAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnPublic)
                    .addComponent(txtDonor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnOrg)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String donor = txtDonor.getText();
        DefaultTableModel model = (DefaultTableModel) tableDonations.getModel();
        model.setRowCount(0);
        
        for(Donation d:ecosystem.getDonationDirectory().getDonationList()){
            if(d.getDonor().equals(donor)){
                Object[] row = new Object[4];
                row[0] = d.getId();
                row[1] = d.getDonor();
                row[2] = d.getAmount();
                SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
                Date date = d.getDate();
                row[3] = ft.format(date);
                
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void rbtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAllActionPerformed
        // TODO add your handling code here:
        populateAllTable();
    }//GEN-LAST:event_rbtnAllActionPerformed

    private void rbtnPublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPublicActionPerformed
        // TODO add your handling code here:
        populatePublicTable();
    }//GEN-LAST:event_rbtnPublicActionPerformed

    private void rbtnOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOrgActionPerformed
        // TODO add your handling code here:
        populateOrgTable();
    }//GEN-LAST:event_rbtnOrgActionPerformed

    private void txtDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonorActionPerformed


    public void populateAllTable(){
        DefaultTableModel model = (DefaultTableModel) tableDonations.getModel();
        model.setRowCount(0);
        
        for(Donation donation:ecosystem.getDonationDirectory().getDonationList()){
            
                Object[] row = new Object[4];
                row[0] = donation.getId();
                row[1] = donation.getDonor();
                row[2] = donation.getAmount();
                SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
                Date date = donation.getDate();
                row[3] = ft.format(date);
       
            
                model.addRow(row);
            
       }
        
    }
    
    public void populatePublicTable(){
        DefaultTableModel model = (DefaultTableModel) tableDonations.getModel();
        model.setRowCount(0);
        
        for(Donation donation:ecosystem.getDonationDirectory().getDonationList()){
            if(donation.isIsPublic()==true){
                Object[] row = new Object[4];
                row[0] = donation.getId();
                row[1] = donation.getDonor();
                row[2] = donation.getAmount();
                SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
                Date date = donation.getDate();
                row[3] = ft.format(date);
       
            
                model.addRow(row);
            }
       }
        
    }
    
    public void populateOrgTable(){
        DefaultTableModel model = (DefaultTableModel) tableDonations.getModel();
        model.setRowCount(0);
        
        for(Donation donation:ecosystem.getDonationDirectory().getDonationList()){
            if(donation.isIsPublic()==false){
                Object[] row = new Object[4];
                row[0] = donation.getId();
                row[1] = donation.getDonor();
                row[2] = donation.getAmount();
                SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");
                Date date = donation.getDate();
                row[3] = ft.format(date);
       
            
                model.addRow(row);
            }
       }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel lblPublic;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rbtnAll;
    private javax.swing.JRadioButton rbtnOrg;
    private javax.swing.JRadioButton rbtnPublic;
    private javax.swing.JTable tableDonations;
    private javax.swing.JTextField txtDonor;
    // End of variables declaration//GEN-END:variables
}
